server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: partner-back-service
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/match?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=CST&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  # session 失效时间
  session:
    timeout: 84600
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
 #   password: 123456
    lettuce:
      pool:
        max-active: 32
        min-idle: 8
        max-idle: 16
knife4j:
  enable: true
  # Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




